version: '3.8'

services:
  trip_management:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/trip_db
      - spring.datasource.username=trip_user
      - spring.datasource.password=trip_password
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.hibernate.ddl-auto=create-drop

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  
    ports:
      - "3000:5173" 

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: trip_db
      POSTGRES_USER: trip_user
      POSTGRES_PASSWORD: trip_password
    ports:
      - "5432:5432"
